application: mutacritic
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: handlers.main.app

- url: /videojuegos/nuevo
  script: handlers.videojuegos.nuevo.app
  login: required

- url: /videojuegos/modifica
  script: handlers.videojuegos.modifica.app
  login: required

- url: /videojuegos/elimina
  script: handlers.videojuegos.elimina.app
  login: required

- url: /comentarios/lista
  script: handlers.comentarios.lista.app

- url: /comentarios/elimina
  script: handlers.comentarios.elimina.app
  login: required

- url: /comentarios/nuevo
  script: handlers.comentarios.nuevo.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"
